/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.2.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Eve.Api.Client.SwaggerDateConverter;

namespace Eve.Api.Model
{
    /// <summary>
    /// 200 ok object
    /// </summary>
    [DataContract]
    public partial class GetCharactersCharacterIdStandings200Ok :  IEquatable<GetCharactersCharacterIdStandings200Ok>, IValidatableObject
    {
        /// <summary>
        /// from_type string
        /// </summary>
        /// <value>from_type string</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum FromTypeEnum
        {
            
            /// <summary>
            /// Enum Agent for "agent"
            /// </summary>
            [EnumMember(Value = "agent")]
            Agent,
            
            /// <summary>
            /// Enum Npccorp for "npc_corp"
            /// </summary>
            [EnumMember(Value = "npc_corp")]
            Npccorp,
            
            /// <summary>
            /// Enum Faction for "faction"
            /// </summary>
            [EnumMember(Value = "faction")]
            Faction
        }

        /// <summary>
        /// from_type string
        /// </summary>
        /// <value>from_type string</value>
        [DataMember(Name="from_type", EmitDefaultValue=false)]
        public FromTypeEnum? FromType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetCharactersCharacterIdStandings200Ok" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetCharactersCharacterIdStandings200Ok() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetCharactersCharacterIdStandings200Ok" /> class.
        /// </summary>
        /// <param name="FromId">from_id integer (required).</param>
        /// <param name="FromType">from_type string (required).</param>
        /// <param name="Standing">standing number (required).</param>
        public GetCharactersCharacterIdStandings200Ok(int? FromId = default(int?), FromTypeEnum? FromType = default(FromTypeEnum?), float? Standing = default(float?))
        {
            // to ensure "FromId" is required (not null)
            if (FromId == null)
            {
                throw new InvalidDataException("FromId is a required property for GetCharactersCharacterIdStandings200Ok and cannot be null");
            }
            else
            {
                this.FromId = FromId;
            }
            // to ensure "FromType" is required (not null)
            if (FromType == null)
            {
                throw new InvalidDataException("FromType is a required property for GetCharactersCharacterIdStandings200Ok and cannot be null");
            }
            else
            {
                this.FromType = FromType;
            }
            // to ensure "Standing" is required (not null)
            if (Standing == null)
            {
                throw new InvalidDataException("Standing is a required property for GetCharactersCharacterIdStandings200Ok and cannot be null");
            }
            else
            {
                this.Standing = Standing;
            }
        }
        
        /// <summary>
        /// from_id integer
        /// </summary>
        /// <value>from_id integer</value>
        [DataMember(Name="from_id", EmitDefaultValue=false)]
        public int? FromId { get; set; }


        /// <summary>
        /// standing number
        /// </summary>
        /// <value>standing number</value>
        [DataMember(Name="standing", EmitDefaultValue=false)]
        public float? Standing { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetCharactersCharacterIdStandings200Ok {\n");
            sb.Append("  FromId: ").Append(FromId).Append("\n");
            sb.Append("  FromType: ").Append(FromType).Append("\n");
            sb.Append("  Standing: ").Append(Standing).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetCharactersCharacterIdStandings200Ok);
        }

        /// <summary>
        /// Returns true if GetCharactersCharacterIdStandings200Ok instances are equal
        /// </summary>
        /// <param name="input">Instance of GetCharactersCharacterIdStandings200Ok to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetCharactersCharacterIdStandings200Ok input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.FromId == input.FromId ||
                    (this.FromId != null &&
                    this.FromId.Equals(input.FromId))
                ) && 
                (
                    this.FromType == input.FromType ||
                    (this.FromType != null &&
                    this.FromType.Equals(input.FromType))
                ) && 
                (
                    this.Standing == input.Standing ||
                    (this.Standing != null &&
                    this.Standing.Equals(input.Standing))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FromId != null)
                    hashCode = hashCode * 59 + this.FromId.GetHashCode();
                if (this.FromType != null)
                    hashCode = hashCode * 59 + this.FromType.GetHashCode();
                if (this.Standing != null)
                    hashCode = hashCode * 59 + this.Standing.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
