/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.2.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Eve.Api.Client.SwaggerDateConverter;

namespace Eve.Api.Model
{
    /// <summary>
    /// 200 ok object
    /// </summary>
    [DataContract]
    public partial class GetCorporationsCorporationIdRoles200Ok :  IEquatable<GetCorporationsCorporationIdRoles200Ok>, IValidatableObject
    {

        /// <summary>
        /// grantable_role string
        /// </summary>
        /// <value>grantable_role string</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum GrantableRolesEnum
        {
            
            /// <summary>
            /// Enum AccountTake1 for "Account_Take_1"
            /// </summary>
            [EnumMember(Value = "Account_Take_1")]
            AccountTake1,
            
            /// <summary>
            /// Enum AccountTake2 for "Account_Take_2"
            /// </summary>
            [EnumMember(Value = "Account_Take_2")]
            AccountTake2,
            
            /// <summary>
            /// Enum AccountTake3 for "Account_Take_3"
            /// </summary>
            [EnumMember(Value = "Account_Take_3")]
            AccountTake3,
            
            /// <summary>
            /// Enum AccountTake4 for "Account_Take_4"
            /// </summary>
            [EnumMember(Value = "Account_Take_4")]
            AccountTake4,
            
            /// <summary>
            /// Enum AccountTake5 for "Account_Take_5"
            /// </summary>
            [EnumMember(Value = "Account_Take_5")]
            AccountTake5,
            
            /// <summary>
            /// Enum AccountTake6 for "Account_Take_6"
            /// </summary>
            [EnumMember(Value = "Account_Take_6")]
            AccountTake6,
            
            /// <summary>
            /// Enum AccountTake7 for "Account_Take_7"
            /// </summary>
            [EnumMember(Value = "Account_Take_7")]
            AccountTake7,
            
            /// <summary>
            /// Enum Accountant for "Accountant"
            /// </summary>
            [EnumMember(Value = "Accountant")]
            Accountant,
            
            /// <summary>
            /// Enum Auditor for "Auditor"
            /// </summary>
            [EnumMember(Value = "Auditor")]
            Auditor,
            
            /// <summary>
            /// Enum CommunicationsOfficer for "Communications_Officer"
            /// </summary>
            [EnumMember(Value = "Communications_Officer")]
            CommunicationsOfficer,
            
            /// <summary>
            /// Enum ConfigEquipment for "Config_Equipment"
            /// </summary>
            [EnumMember(Value = "Config_Equipment")]
            ConfigEquipment,
            
            /// <summary>
            /// Enum ConfigStarbaseEquipment for "Config_Starbase_Equipment"
            /// </summary>
            [EnumMember(Value = "Config_Starbase_Equipment")]
            ConfigStarbaseEquipment,
            
            /// <summary>
            /// Enum ContainerTake1 for "Container_Take_1"
            /// </summary>
            [EnumMember(Value = "Container_Take_1")]
            ContainerTake1,
            
            /// <summary>
            /// Enum ContainerTake2 for "Container_Take_2"
            /// </summary>
            [EnumMember(Value = "Container_Take_2")]
            ContainerTake2,
            
            /// <summary>
            /// Enum ContainerTake3 for "Container_Take_3"
            /// </summary>
            [EnumMember(Value = "Container_Take_3")]
            ContainerTake3,
            
            /// <summary>
            /// Enum ContainerTake4 for "Container_Take_4"
            /// </summary>
            [EnumMember(Value = "Container_Take_4")]
            ContainerTake4,
            
            /// <summary>
            /// Enum ContainerTake5 for "Container_Take_5"
            /// </summary>
            [EnumMember(Value = "Container_Take_5")]
            ContainerTake5,
            
            /// <summary>
            /// Enum ContainerTake6 for "Container_Take_6"
            /// </summary>
            [EnumMember(Value = "Container_Take_6")]
            ContainerTake6,
            
            /// <summary>
            /// Enum ContainerTake7 for "Container_Take_7"
            /// </summary>
            [EnumMember(Value = "Container_Take_7")]
            ContainerTake7,
            
            /// <summary>
            /// Enum ContractManager for "Contract_Manager"
            /// </summary>
            [EnumMember(Value = "Contract_Manager")]
            ContractManager,
            
            /// <summary>
            /// Enum Diplomat for "Diplomat"
            /// </summary>
            [EnumMember(Value = "Diplomat")]
            Diplomat,
            
            /// <summary>
            /// Enum Director for "Director"
            /// </summary>
            [EnumMember(Value = "Director")]
            Director,
            
            /// <summary>
            /// Enum FactoryManager for "Factory_Manager"
            /// </summary>
            [EnumMember(Value = "Factory_Manager")]
            FactoryManager,
            
            /// <summary>
            /// Enum FittingManager for "Fitting_Manager"
            /// </summary>
            [EnumMember(Value = "Fitting_Manager")]
            FittingManager,
            
            /// <summary>
            /// Enum HangarQuery1 for "Hangar_Query_1"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_1")]
            HangarQuery1,
            
            /// <summary>
            /// Enum HangarQuery2 for "Hangar_Query_2"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_2")]
            HangarQuery2,
            
            /// <summary>
            /// Enum HangarQuery3 for "Hangar_Query_3"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_3")]
            HangarQuery3,
            
            /// <summary>
            /// Enum HangarQuery4 for "Hangar_Query_4"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_4")]
            HangarQuery4,
            
            /// <summary>
            /// Enum HangarQuery5 for "Hangar_Query_5"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_5")]
            HangarQuery5,
            
            /// <summary>
            /// Enum HangarQuery6 for "Hangar_Query_6"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_6")]
            HangarQuery6,
            
            /// <summary>
            /// Enum HangarQuery7 for "Hangar_Query_7"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_7")]
            HangarQuery7,
            
            /// <summary>
            /// Enum HangarTake1 for "Hangar_Take_1"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_1")]
            HangarTake1,
            
            /// <summary>
            /// Enum HangarTake2 for "Hangar_Take_2"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_2")]
            HangarTake2,
            
            /// <summary>
            /// Enum HangarTake3 for "Hangar_Take_3"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_3")]
            HangarTake3,
            
            /// <summary>
            /// Enum HangarTake4 for "Hangar_Take_4"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_4")]
            HangarTake4,
            
            /// <summary>
            /// Enum HangarTake5 for "Hangar_Take_5"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_5")]
            HangarTake5,
            
            /// <summary>
            /// Enum HangarTake6 for "Hangar_Take_6"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_6")]
            HangarTake6,
            
            /// <summary>
            /// Enum HangarTake7 for "Hangar_Take_7"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_7")]
            HangarTake7,
            
            /// <summary>
            /// Enum JuniorAccountant for "Junior_Accountant"
            /// </summary>
            [EnumMember(Value = "Junior_Accountant")]
            JuniorAccountant,
            
            /// <summary>
            /// Enum PersonnelManager for "Personnel_Manager"
            /// </summary>
            [EnumMember(Value = "Personnel_Manager")]
            PersonnelManager,
            
            /// <summary>
            /// Enum RentFactoryFacility for "Rent_Factory_Facility"
            /// </summary>
            [EnumMember(Value = "Rent_Factory_Facility")]
            RentFactoryFacility,
            
            /// <summary>
            /// Enum RentOffice for "Rent_Office"
            /// </summary>
            [EnumMember(Value = "Rent_Office")]
            RentOffice,
            
            /// <summary>
            /// Enum RentResearchFacility for "Rent_Research_Facility"
            /// </summary>
            [EnumMember(Value = "Rent_Research_Facility")]
            RentResearchFacility,
            
            /// <summary>
            /// Enum SecurityOfficer for "Security_Officer"
            /// </summary>
            [EnumMember(Value = "Security_Officer")]
            SecurityOfficer,
            
            /// <summary>
            /// Enum StarbaseDefenseOperator for "Starbase_Defense_Operator"
            /// </summary>
            [EnumMember(Value = "Starbase_Defense_Operator")]
            StarbaseDefenseOperator,
            
            /// <summary>
            /// Enum StarbaseFuelTechnician for "Starbase_Fuel_Technician"
            /// </summary>
            [EnumMember(Value = "Starbase_Fuel_Technician")]
            StarbaseFuelTechnician,
            
            /// <summary>
            /// Enum StationManager for "Station_Manager"
            /// </summary>
            [EnumMember(Value = "Station_Manager")]
            StationManager,
            
            /// <summary>
            /// Enum Trader for "Trader"
            /// </summary>
            [EnumMember(Value = "Trader")]
            Trader
        }


        /// <summary>
        /// grantable_roles_at_base string
        /// </summary>
        /// <value>grantable_roles_at_base string</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum GrantableRolesAtBaseEnum
        {
            
            /// <summary>
            /// Enum AccountTake1 for "Account_Take_1"
            /// </summary>
            [EnumMember(Value = "Account_Take_1")]
            AccountTake1,
            
            /// <summary>
            /// Enum AccountTake2 for "Account_Take_2"
            /// </summary>
            [EnumMember(Value = "Account_Take_2")]
            AccountTake2,
            
            /// <summary>
            /// Enum AccountTake3 for "Account_Take_3"
            /// </summary>
            [EnumMember(Value = "Account_Take_3")]
            AccountTake3,
            
            /// <summary>
            /// Enum AccountTake4 for "Account_Take_4"
            /// </summary>
            [EnumMember(Value = "Account_Take_4")]
            AccountTake4,
            
            /// <summary>
            /// Enum AccountTake5 for "Account_Take_5"
            /// </summary>
            [EnumMember(Value = "Account_Take_5")]
            AccountTake5,
            
            /// <summary>
            /// Enum AccountTake6 for "Account_Take_6"
            /// </summary>
            [EnumMember(Value = "Account_Take_6")]
            AccountTake6,
            
            /// <summary>
            /// Enum AccountTake7 for "Account_Take_7"
            /// </summary>
            [EnumMember(Value = "Account_Take_7")]
            AccountTake7,
            
            /// <summary>
            /// Enum Accountant for "Accountant"
            /// </summary>
            [EnumMember(Value = "Accountant")]
            Accountant,
            
            /// <summary>
            /// Enum Auditor for "Auditor"
            /// </summary>
            [EnumMember(Value = "Auditor")]
            Auditor,
            
            /// <summary>
            /// Enum CommunicationsOfficer for "Communications_Officer"
            /// </summary>
            [EnumMember(Value = "Communications_Officer")]
            CommunicationsOfficer,
            
            /// <summary>
            /// Enum ConfigEquipment for "Config_Equipment"
            /// </summary>
            [EnumMember(Value = "Config_Equipment")]
            ConfigEquipment,
            
            /// <summary>
            /// Enum ConfigStarbaseEquipment for "Config_Starbase_Equipment"
            /// </summary>
            [EnumMember(Value = "Config_Starbase_Equipment")]
            ConfigStarbaseEquipment,
            
            /// <summary>
            /// Enum ContainerTake1 for "Container_Take_1"
            /// </summary>
            [EnumMember(Value = "Container_Take_1")]
            ContainerTake1,
            
            /// <summary>
            /// Enum ContainerTake2 for "Container_Take_2"
            /// </summary>
            [EnumMember(Value = "Container_Take_2")]
            ContainerTake2,
            
            /// <summary>
            /// Enum ContainerTake3 for "Container_Take_3"
            /// </summary>
            [EnumMember(Value = "Container_Take_3")]
            ContainerTake3,
            
            /// <summary>
            /// Enum ContainerTake4 for "Container_Take_4"
            /// </summary>
            [EnumMember(Value = "Container_Take_4")]
            ContainerTake4,
            
            /// <summary>
            /// Enum ContainerTake5 for "Container_Take_5"
            /// </summary>
            [EnumMember(Value = "Container_Take_5")]
            ContainerTake5,
            
            /// <summary>
            /// Enum ContainerTake6 for "Container_Take_6"
            /// </summary>
            [EnumMember(Value = "Container_Take_6")]
            ContainerTake6,
            
            /// <summary>
            /// Enum ContainerTake7 for "Container_Take_7"
            /// </summary>
            [EnumMember(Value = "Container_Take_7")]
            ContainerTake7,
            
            /// <summary>
            /// Enum ContractManager for "Contract_Manager"
            /// </summary>
            [EnumMember(Value = "Contract_Manager")]
            ContractManager,
            
            /// <summary>
            /// Enum Diplomat for "Diplomat"
            /// </summary>
            [EnumMember(Value = "Diplomat")]
            Diplomat,
            
            /// <summary>
            /// Enum Director for "Director"
            /// </summary>
            [EnumMember(Value = "Director")]
            Director,
            
            /// <summary>
            /// Enum FactoryManager for "Factory_Manager"
            /// </summary>
            [EnumMember(Value = "Factory_Manager")]
            FactoryManager,
            
            /// <summary>
            /// Enum FittingManager for "Fitting_Manager"
            /// </summary>
            [EnumMember(Value = "Fitting_Manager")]
            FittingManager,
            
            /// <summary>
            /// Enum HangarQuery1 for "Hangar_Query_1"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_1")]
            HangarQuery1,
            
            /// <summary>
            /// Enum HangarQuery2 for "Hangar_Query_2"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_2")]
            HangarQuery2,
            
            /// <summary>
            /// Enum HangarQuery3 for "Hangar_Query_3"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_3")]
            HangarQuery3,
            
            /// <summary>
            /// Enum HangarQuery4 for "Hangar_Query_4"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_4")]
            HangarQuery4,
            
            /// <summary>
            /// Enum HangarQuery5 for "Hangar_Query_5"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_5")]
            HangarQuery5,
            
            /// <summary>
            /// Enum HangarQuery6 for "Hangar_Query_6"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_6")]
            HangarQuery6,
            
            /// <summary>
            /// Enum HangarQuery7 for "Hangar_Query_7"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_7")]
            HangarQuery7,
            
            /// <summary>
            /// Enum HangarTake1 for "Hangar_Take_1"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_1")]
            HangarTake1,
            
            /// <summary>
            /// Enum HangarTake2 for "Hangar_Take_2"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_2")]
            HangarTake2,
            
            /// <summary>
            /// Enum HangarTake3 for "Hangar_Take_3"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_3")]
            HangarTake3,
            
            /// <summary>
            /// Enum HangarTake4 for "Hangar_Take_4"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_4")]
            HangarTake4,
            
            /// <summary>
            /// Enum HangarTake5 for "Hangar_Take_5"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_5")]
            HangarTake5,
            
            /// <summary>
            /// Enum HangarTake6 for "Hangar_Take_6"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_6")]
            HangarTake6,
            
            /// <summary>
            /// Enum HangarTake7 for "Hangar_Take_7"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_7")]
            HangarTake7,
            
            /// <summary>
            /// Enum JuniorAccountant for "Junior_Accountant"
            /// </summary>
            [EnumMember(Value = "Junior_Accountant")]
            JuniorAccountant,
            
            /// <summary>
            /// Enum PersonnelManager for "Personnel_Manager"
            /// </summary>
            [EnumMember(Value = "Personnel_Manager")]
            PersonnelManager,
            
            /// <summary>
            /// Enum RentFactoryFacility for "Rent_Factory_Facility"
            /// </summary>
            [EnumMember(Value = "Rent_Factory_Facility")]
            RentFactoryFacility,
            
            /// <summary>
            /// Enum RentOffice for "Rent_Office"
            /// </summary>
            [EnumMember(Value = "Rent_Office")]
            RentOffice,
            
            /// <summary>
            /// Enum RentResearchFacility for "Rent_Research_Facility"
            /// </summary>
            [EnumMember(Value = "Rent_Research_Facility")]
            RentResearchFacility,
            
            /// <summary>
            /// Enum SecurityOfficer for "Security_Officer"
            /// </summary>
            [EnumMember(Value = "Security_Officer")]
            SecurityOfficer,
            
            /// <summary>
            /// Enum StarbaseDefenseOperator for "Starbase_Defense_Operator"
            /// </summary>
            [EnumMember(Value = "Starbase_Defense_Operator")]
            StarbaseDefenseOperator,
            
            /// <summary>
            /// Enum StarbaseFuelTechnician for "Starbase_Fuel_Technician"
            /// </summary>
            [EnumMember(Value = "Starbase_Fuel_Technician")]
            StarbaseFuelTechnician,
            
            /// <summary>
            /// Enum StationManager for "Station_Manager"
            /// </summary>
            [EnumMember(Value = "Station_Manager")]
            StationManager,
            
            /// <summary>
            /// Enum Trader for "Trader"
            /// </summary>
            [EnumMember(Value = "Trader")]
            Trader
        }


        /// <summary>
        /// grantable_roles_at_hq string
        /// </summary>
        /// <value>grantable_roles_at_hq string</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum GrantableRolesAtHqEnum
        {
            
            /// <summary>
            /// Enum AccountTake1 for "Account_Take_1"
            /// </summary>
            [EnumMember(Value = "Account_Take_1")]
            AccountTake1,
            
            /// <summary>
            /// Enum AccountTake2 for "Account_Take_2"
            /// </summary>
            [EnumMember(Value = "Account_Take_2")]
            AccountTake2,
            
            /// <summary>
            /// Enum AccountTake3 for "Account_Take_3"
            /// </summary>
            [EnumMember(Value = "Account_Take_3")]
            AccountTake3,
            
            /// <summary>
            /// Enum AccountTake4 for "Account_Take_4"
            /// </summary>
            [EnumMember(Value = "Account_Take_4")]
            AccountTake4,
            
            /// <summary>
            /// Enum AccountTake5 for "Account_Take_5"
            /// </summary>
            [EnumMember(Value = "Account_Take_5")]
            AccountTake5,
            
            /// <summary>
            /// Enum AccountTake6 for "Account_Take_6"
            /// </summary>
            [EnumMember(Value = "Account_Take_6")]
            AccountTake6,
            
            /// <summary>
            /// Enum AccountTake7 for "Account_Take_7"
            /// </summary>
            [EnumMember(Value = "Account_Take_7")]
            AccountTake7,
            
            /// <summary>
            /// Enum Accountant for "Accountant"
            /// </summary>
            [EnumMember(Value = "Accountant")]
            Accountant,
            
            /// <summary>
            /// Enum Auditor for "Auditor"
            /// </summary>
            [EnumMember(Value = "Auditor")]
            Auditor,
            
            /// <summary>
            /// Enum CommunicationsOfficer for "Communications_Officer"
            /// </summary>
            [EnumMember(Value = "Communications_Officer")]
            CommunicationsOfficer,
            
            /// <summary>
            /// Enum ConfigEquipment for "Config_Equipment"
            /// </summary>
            [EnumMember(Value = "Config_Equipment")]
            ConfigEquipment,
            
            /// <summary>
            /// Enum ConfigStarbaseEquipment for "Config_Starbase_Equipment"
            /// </summary>
            [EnumMember(Value = "Config_Starbase_Equipment")]
            ConfigStarbaseEquipment,
            
            /// <summary>
            /// Enum ContainerTake1 for "Container_Take_1"
            /// </summary>
            [EnumMember(Value = "Container_Take_1")]
            ContainerTake1,
            
            /// <summary>
            /// Enum ContainerTake2 for "Container_Take_2"
            /// </summary>
            [EnumMember(Value = "Container_Take_2")]
            ContainerTake2,
            
            /// <summary>
            /// Enum ContainerTake3 for "Container_Take_3"
            /// </summary>
            [EnumMember(Value = "Container_Take_3")]
            ContainerTake3,
            
            /// <summary>
            /// Enum ContainerTake4 for "Container_Take_4"
            /// </summary>
            [EnumMember(Value = "Container_Take_4")]
            ContainerTake4,
            
            /// <summary>
            /// Enum ContainerTake5 for "Container_Take_5"
            /// </summary>
            [EnumMember(Value = "Container_Take_5")]
            ContainerTake5,
            
            /// <summary>
            /// Enum ContainerTake6 for "Container_Take_6"
            /// </summary>
            [EnumMember(Value = "Container_Take_6")]
            ContainerTake6,
            
            /// <summary>
            /// Enum ContainerTake7 for "Container_Take_7"
            /// </summary>
            [EnumMember(Value = "Container_Take_7")]
            ContainerTake7,
            
            /// <summary>
            /// Enum ContractManager for "Contract_Manager"
            /// </summary>
            [EnumMember(Value = "Contract_Manager")]
            ContractManager,
            
            /// <summary>
            /// Enum Diplomat for "Diplomat"
            /// </summary>
            [EnumMember(Value = "Diplomat")]
            Diplomat,
            
            /// <summary>
            /// Enum Director for "Director"
            /// </summary>
            [EnumMember(Value = "Director")]
            Director,
            
            /// <summary>
            /// Enum FactoryManager for "Factory_Manager"
            /// </summary>
            [EnumMember(Value = "Factory_Manager")]
            FactoryManager,
            
            /// <summary>
            /// Enum FittingManager for "Fitting_Manager"
            /// </summary>
            [EnumMember(Value = "Fitting_Manager")]
            FittingManager,
            
            /// <summary>
            /// Enum HangarQuery1 for "Hangar_Query_1"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_1")]
            HangarQuery1,
            
            /// <summary>
            /// Enum HangarQuery2 for "Hangar_Query_2"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_2")]
            HangarQuery2,
            
            /// <summary>
            /// Enum HangarQuery3 for "Hangar_Query_3"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_3")]
            HangarQuery3,
            
            /// <summary>
            /// Enum HangarQuery4 for "Hangar_Query_4"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_4")]
            HangarQuery4,
            
            /// <summary>
            /// Enum HangarQuery5 for "Hangar_Query_5"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_5")]
            HangarQuery5,
            
            /// <summary>
            /// Enum HangarQuery6 for "Hangar_Query_6"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_6")]
            HangarQuery6,
            
            /// <summary>
            /// Enum HangarQuery7 for "Hangar_Query_7"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_7")]
            HangarQuery7,
            
            /// <summary>
            /// Enum HangarTake1 for "Hangar_Take_1"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_1")]
            HangarTake1,
            
            /// <summary>
            /// Enum HangarTake2 for "Hangar_Take_2"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_2")]
            HangarTake2,
            
            /// <summary>
            /// Enum HangarTake3 for "Hangar_Take_3"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_3")]
            HangarTake3,
            
            /// <summary>
            /// Enum HangarTake4 for "Hangar_Take_4"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_4")]
            HangarTake4,
            
            /// <summary>
            /// Enum HangarTake5 for "Hangar_Take_5"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_5")]
            HangarTake5,
            
            /// <summary>
            /// Enum HangarTake6 for "Hangar_Take_6"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_6")]
            HangarTake6,
            
            /// <summary>
            /// Enum HangarTake7 for "Hangar_Take_7"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_7")]
            HangarTake7,
            
            /// <summary>
            /// Enum JuniorAccountant for "Junior_Accountant"
            /// </summary>
            [EnumMember(Value = "Junior_Accountant")]
            JuniorAccountant,
            
            /// <summary>
            /// Enum PersonnelManager for "Personnel_Manager"
            /// </summary>
            [EnumMember(Value = "Personnel_Manager")]
            PersonnelManager,
            
            /// <summary>
            /// Enum RentFactoryFacility for "Rent_Factory_Facility"
            /// </summary>
            [EnumMember(Value = "Rent_Factory_Facility")]
            RentFactoryFacility,
            
            /// <summary>
            /// Enum RentOffice for "Rent_Office"
            /// </summary>
            [EnumMember(Value = "Rent_Office")]
            RentOffice,
            
            /// <summary>
            /// Enum RentResearchFacility for "Rent_Research_Facility"
            /// </summary>
            [EnumMember(Value = "Rent_Research_Facility")]
            RentResearchFacility,
            
            /// <summary>
            /// Enum SecurityOfficer for "Security_Officer"
            /// </summary>
            [EnumMember(Value = "Security_Officer")]
            SecurityOfficer,
            
            /// <summary>
            /// Enum StarbaseDefenseOperator for "Starbase_Defense_Operator"
            /// </summary>
            [EnumMember(Value = "Starbase_Defense_Operator")]
            StarbaseDefenseOperator,
            
            /// <summary>
            /// Enum StarbaseFuelTechnician for "Starbase_Fuel_Technician"
            /// </summary>
            [EnumMember(Value = "Starbase_Fuel_Technician")]
            StarbaseFuelTechnician,
            
            /// <summary>
            /// Enum StationManager for "Station_Manager"
            /// </summary>
            [EnumMember(Value = "Station_Manager")]
            StationManager,
            
            /// <summary>
            /// Enum Trader for "Trader"
            /// </summary>
            [EnumMember(Value = "Trader")]
            Trader
        }


        /// <summary>
        /// grantable_roles_at_other string
        /// </summary>
        /// <value>grantable_roles_at_other string</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum GrantableRolesAtOtherEnum
        {
            
            /// <summary>
            /// Enum AccountTake1 for "Account_Take_1"
            /// </summary>
            [EnumMember(Value = "Account_Take_1")]
            AccountTake1,
            
            /// <summary>
            /// Enum AccountTake2 for "Account_Take_2"
            /// </summary>
            [EnumMember(Value = "Account_Take_2")]
            AccountTake2,
            
            /// <summary>
            /// Enum AccountTake3 for "Account_Take_3"
            /// </summary>
            [EnumMember(Value = "Account_Take_3")]
            AccountTake3,
            
            /// <summary>
            /// Enum AccountTake4 for "Account_Take_4"
            /// </summary>
            [EnumMember(Value = "Account_Take_4")]
            AccountTake4,
            
            /// <summary>
            /// Enum AccountTake5 for "Account_Take_5"
            /// </summary>
            [EnumMember(Value = "Account_Take_5")]
            AccountTake5,
            
            /// <summary>
            /// Enum AccountTake6 for "Account_Take_6"
            /// </summary>
            [EnumMember(Value = "Account_Take_6")]
            AccountTake6,
            
            /// <summary>
            /// Enum AccountTake7 for "Account_Take_7"
            /// </summary>
            [EnumMember(Value = "Account_Take_7")]
            AccountTake7,
            
            /// <summary>
            /// Enum Accountant for "Accountant"
            /// </summary>
            [EnumMember(Value = "Accountant")]
            Accountant,
            
            /// <summary>
            /// Enum Auditor for "Auditor"
            /// </summary>
            [EnumMember(Value = "Auditor")]
            Auditor,
            
            /// <summary>
            /// Enum CommunicationsOfficer for "Communications_Officer"
            /// </summary>
            [EnumMember(Value = "Communications_Officer")]
            CommunicationsOfficer,
            
            /// <summary>
            /// Enum ConfigEquipment for "Config_Equipment"
            /// </summary>
            [EnumMember(Value = "Config_Equipment")]
            ConfigEquipment,
            
            /// <summary>
            /// Enum ConfigStarbaseEquipment for "Config_Starbase_Equipment"
            /// </summary>
            [EnumMember(Value = "Config_Starbase_Equipment")]
            ConfigStarbaseEquipment,
            
            /// <summary>
            /// Enum ContainerTake1 for "Container_Take_1"
            /// </summary>
            [EnumMember(Value = "Container_Take_1")]
            ContainerTake1,
            
            /// <summary>
            /// Enum ContainerTake2 for "Container_Take_2"
            /// </summary>
            [EnumMember(Value = "Container_Take_2")]
            ContainerTake2,
            
            /// <summary>
            /// Enum ContainerTake3 for "Container_Take_3"
            /// </summary>
            [EnumMember(Value = "Container_Take_3")]
            ContainerTake3,
            
            /// <summary>
            /// Enum ContainerTake4 for "Container_Take_4"
            /// </summary>
            [EnumMember(Value = "Container_Take_4")]
            ContainerTake4,
            
            /// <summary>
            /// Enum ContainerTake5 for "Container_Take_5"
            /// </summary>
            [EnumMember(Value = "Container_Take_5")]
            ContainerTake5,
            
            /// <summary>
            /// Enum ContainerTake6 for "Container_Take_6"
            /// </summary>
            [EnumMember(Value = "Container_Take_6")]
            ContainerTake6,
            
            /// <summary>
            /// Enum ContainerTake7 for "Container_Take_7"
            /// </summary>
            [EnumMember(Value = "Container_Take_7")]
            ContainerTake7,
            
            /// <summary>
            /// Enum ContractManager for "Contract_Manager"
            /// </summary>
            [EnumMember(Value = "Contract_Manager")]
            ContractManager,
            
            /// <summary>
            /// Enum Diplomat for "Diplomat"
            /// </summary>
            [EnumMember(Value = "Diplomat")]
            Diplomat,
            
            /// <summary>
            /// Enum Director for "Director"
            /// </summary>
            [EnumMember(Value = "Director")]
            Director,
            
            /// <summary>
            /// Enum FactoryManager for "Factory_Manager"
            /// </summary>
            [EnumMember(Value = "Factory_Manager")]
            FactoryManager,
            
            /// <summary>
            /// Enum FittingManager for "Fitting_Manager"
            /// </summary>
            [EnumMember(Value = "Fitting_Manager")]
            FittingManager,
            
            /// <summary>
            /// Enum HangarQuery1 for "Hangar_Query_1"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_1")]
            HangarQuery1,
            
            /// <summary>
            /// Enum HangarQuery2 for "Hangar_Query_2"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_2")]
            HangarQuery2,
            
            /// <summary>
            /// Enum HangarQuery3 for "Hangar_Query_3"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_3")]
            HangarQuery3,
            
            /// <summary>
            /// Enum HangarQuery4 for "Hangar_Query_4"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_4")]
            HangarQuery4,
            
            /// <summary>
            /// Enum HangarQuery5 for "Hangar_Query_5"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_5")]
            HangarQuery5,
            
            /// <summary>
            /// Enum HangarQuery6 for "Hangar_Query_6"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_6")]
            HangarQuery6,
            
            /// <summary>
            /// Enum HangarQuery7 for "Hangar_Query_7"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_7")]
            HangarQuery7,
            
            /// <summary>
            /// Enum HangarTake1 for "Hangar_Take_1"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_1")]
            HangarTake1,
            
            /// <summary>
            /// Enum HangarTake2 for "Hangar_Take_2"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_2")]
            HangarTake2,
            
            /// <summary>
            /// Enum HangarTake3 for "Hangar_Take_3"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_3")]
            HangarTake3,
            
            /// <summary>
            /// Enum HangarTake4 for "Hangar_Take_4"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_4")]
            HangarTake4,
            
            /// <summary>
            /// Enum HangarTake5 for "Hangar_Take_5"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_5")]
            HangarTake5,
            
            /// <summary>
            /// Enum HangarTake6 for "Hangar_Take_6"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_6")]
            HangarTake6,
            
            /// <summary>
            /// Enum HangarTake7 for "Hangar_Take_7"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_7")]
            HangarTake7,
            
            /// <summary>
            /// Enum JuniorAccountant for "Junior_Accountant"
            /// </summary>
            [EnumMember(Value = "Junior_Accountant")]
            JuniorAccountant,
            
            /// <summary>
            /// Enum PersonnelManager for "Personnel_Manager"
            /// </summary>
            [EnumMember(Value = "Personnel_Manager")]
            PersonnelManager,
            
            /// <summary>
            /// Enum RentFactoryFacility for "Rent_Factory_Facility"
            /// </summary>
            [EnumMember(Value = "Rent_Factory_Facility")]
            RentFactoryFacility,
            
            /// <summary>
            /// Enum RentOffice for "Rent_Office"
            /// </summary>
            [EnumMember(Value = "Rent_Office")]
            RentOffice,
            
            /// <summary>
            /// Enum RentResearchFacility for "Rent_Research_Facility"
            /// </summary>
            [EnumMember(Value = "Rent_Research_Facility")]
            RentResearchFacility,
            
            /// <summary>
            /// Enum SecurityOfficer for "Security_Officer"
            /// </summary>
            [EnumMember(Value = "Security_Officer")]
            SecurityOfficer,
            
            /// <summary>
            /// Enum StarbaseDefenseOperator for "Starbase_Defense_Operator"
            /// </summary>
            [EnumMember(Value = "Starbase_Defense_Operator")]
            StarbaseDefenseOperator,
            
            /// <summary>
            /// Enum StarbaseFuelTechnician for "Starbase_Fuel_Technician"
            /// </summary>
            [EnumMember(Value = "Starbase_Fuel_Technician")]
            StarbaseFuelTechnician,
            
            /// <summary>
            /// Enum StationManager for "Station_Manager"
            /// </summary>
            [EnumMember(Value = "Station_Manager")]
            StationManager,
            
            /// <summary>
            /// Enum Trader for "Trader"
            /// </summary>
            [EnumMember(Value = "Trader")]
            Trader
        }


        /// <summary>
        /// role string
        /// </summary>
        /// <value>role string</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum RolesEnum
        {
            
            /// <summary>
            /// Enum AccountTake1 for "Account_Take_1"
            /// </summary>
            [EnumMember(Value = "Account_Take_1")]
            AccountTake1,
            
            /// <summary>
            /// Enum AccountTake2 for "Account_Take_2"
            /// </summary>
            [EnumMember(Value = "Account_Take_2")]
            AccountTake2,
            
            /// <summary>
            /// Enum AccountTake3 for "Account_Take_3"
            /// </summary>
            [EnumMember(Value = "Account_Take_3")]
            AccountTake3,
            
            /// <summary>
            /// Enum AccountTake4 for "Account_Take_4"
            /// </summary>
            [EnumMember(Value = "Account_Take_4")]
            AccountTake4,
            
            /// <summary>
            /// Enum AccountTake5 for "Account_Take_5"
            /// </summary>
            [EnumMember(Value = "Account_Take_5")]
            AccountTake5,
            
            /// <summary>
            /// Enum AccountTake6 for "Account_Take_6"
            /// </summary>
            [EnumMember(Value = "Account_Take_6")]
            AccountTake6,
            
            /// <summary>
            /// Enum AccountTake7 for "Account_Take_7"
            /// </summary>
            [EnumMember(Value = "Account_Take_7")]
            AccountTake7,
            
            /// <summary>
            /// Enum Accountant for "Accountant"
            /// </summary>
            [EnumMember(Value = "Accountant")]
            Accountant,
            
            /// <summary>
            /// Enum Auditor for "Auditor"
            /// </summary>
            [EnumMember(Value = "Auditor")]
            Auditor,
            
            /// <summary>
            /// Enum CommunicationsOfficer for "Communications_Officer"
            /// </summary>
            [EnumMember(Value = "Communications_Officer")]
            CommunicationsOfficer,
            
            /// <summary>
            /// Enum ConfigEquipment for "Config_Equipment"
            /// </summary>
            [EnumMember(Value = "Config_Equipment")]
            ConfigEquipment,
            
            /// <summary>
            /// Enum ConfigStarbaseEquipment for "Config_Starbase_Equipment"
            /// </summary>
            [EnumMember(Value = "Config_Starbase_Equipment")]
            ConfigStarbaseEquipment,
            
            /// <summary>
            /// Enum ContainerTake1 for "Container_Take_1"
            /// </summary>
            [EnumMember(Value = "Container_Take_1")]
            ContainerTake1,
            
            /// <summary>
            /// Enum ContainerTake2 for "Container_Take_2"
            /// </summary>
            [EnumMember(Value = "Container_Take_2")]
            ContainerTake2,
            
            /// <summary>
            /// Enum ContainerTake3 for "Container_Take_3"
            /// </summary>
            [EnumMember(Value = "Container_Take_3")]
            ContainerTake3,
            
            /// <summary>
            /// Enum ContainerTake4 for "Container_Take_4"
            /// </summary>
            [EnumMember(Value = "Container_Take_4")]
            ContainerTake4,
            
            /// <summary>
            /// Enum ContainerTake5 for "Container_Take_5"
            /// </summary>
            [EnumMember(Value = "Container_Take_5")]
            ContainerTake5,
            
            /// <summary>
            /// Enum ContainerTake6 for "Container_Take_6"
            /// </summary>
            [EnumMember(Value = "Container_Take_6")]
            ContainerTake6,
            
            /// <summary>
            /// Enum ContainerTake7 for "Container_Take_7"
            /// </summary>
            [EnumMember(Value = "Container_Take_7")]
            ContainerTake7,
            
            /// <summary>
            /// Enum ContractManager for "Contract_Manager"
            /// </summary>
            [EnumMember(Value = "Contract_Manager")]
            ContractManager,
            
            /// <summary>
            /// Enum Diplomat for "Diplomat"
            /// </summary>
            [EnumMember(Value = "Diplomat")]
            Diplomat,
            
            /// <summary>
            /// Enum Director for "Director"
            /// </summary>
            [EnumMember(Value = "Director")]
            Director,
            
            /// <summary>
            /// Enum FactoryManager for "Factory_Manager"
            /// </summary>
            [EnumMember(Value = "Factory_Manager")]
            FactoryManager,
            
            /// <summary>
            /// Enum FittingManager for "Fitting_Manager"
            /// </summary>
            [EnumMember(Value = "Fitting_Manager")]
            FittingManager,
            
            /// <summary>
            /// Enum HangarQuery1 for "Hangar_Query_1"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_1")]
            HangarQuery1,
            
            /// <summary>
            /// Enum HangarQuery2 for "Hangar_Query_2"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_2")]
            HangarQuery2,
            
            /// <summary>
            /// Enum HangarQuery3 for "Hangar_Query_3"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_3")]
            HangarQuery3,
            
            /// <summary>
            /// Enum HangarQuery4 for "Hangar_Query_4"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_4")]
            HangarQuery4,
            
            /// <summary>
            /// Enum HangarQuery5 for "Hangar_Query_5"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_5")]
            HangarQuery5,
            
            /// <summary>
            /// Enum HangarQuery6 for "Hangar_Query_6"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_6")]
            HangarQuery6,
            
            /// <summary>
            /// Enum HangarQuery7 for "Hangar_Query_7"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_7")]
            HangarQuery7,
            
            /// <summary>
            /// Enum HangarTake1 for "Hangar_Take_1"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_1")]
            HangarTake1,
            
            /// <summary>
            /// Enum HangarTake2 for "Hangar_Take_2"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_2")]
            HangarTake2,
            
            /// <summary>
            /// Enum HangarTake3 for "Hangar_Take_3"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_3")]
            HangarTake3,
            
            /// <summary>
            /// Enum HangarTake4 for "Hangar_Take_4"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_4")]
            HangarTake4,
            
            /// <summary>
            /// Enum HangarTake5 for "Hangar_Take_5"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_5")]
            HangarTake5,
            
            /// <summary>
            /// Enum HangarTake6 for "Hangar_Take_6"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_6")]
            HangarTake6,
            
            /// <summary>
            /// Enum HangarTake7 for "Hangar_Take_7"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_7")]
            HangarTake7,
            
            /// <summary>
            /// Enum JuniorAccountant for "Junior_Accountant"
            /// </summary>
            [EnumMember(Value = "Junior_Accountant")]
            JuniorAccountant,
            
            /// <summary>
            /// Enum PersonnelManager for "Personnel_Manager"
            /// </summary>
            [EnumMember(Value = "Personnel_Manager")]
            PersonnelManager,
            
            /// <summary>
            /// Enum RentFactoryFacility for "Rent_Factory_Facility"
            /// </summary>
            [EnumMember(Value = "Rent_Factory_Facility")]
            RentFactoryFacility,
            
            /// <summary>
            /// Enum RentOffice for "Rent_Office"
            /// </summary>
            [EnumMember(Value = "Rent_Office")]
            RentOffice,
            
            /// <summary>
            /// Enum RentResearchFacility for "Rent_Research_Facility"
            /// </summary>
            [EnumMember(Value = "Rent_Research_Facility")]
            RentResearchFacility,
            
            /// <summary>
            /// Enum SecurityOfficer for "Security_Officer"
            /// </summary>
            [EnumMember(Value = "Security_Officer")]
            SecurityOfficer,
            
            /// <summary>
            /// Enum StarbaseDefenseOperator for "Starbase_Defense_Operator"
            /// </summary>
            [EnumMember(Value = "Starbase_Defense_Operator")]
            StarbaseDefenseOperator,
            
            /// <summary>
            /// Enum StarbaseFuelTechnician for "Starbase_Fuel_Technician"
            /// </summary>
            [EnumMember(Value = "Starbase_Fuel_Technician")]
            StarbaseFuelTechnician,
            
            /// <summary>
            /// Enum StationManager for "Station_Manager"
            /// </summary>
            [EnumMember(Value = "Station_Manager")]
            StationManager,
            
            /// <summary>
            /// Enum Trader for "Trader"
            /// </summary>
            [EnumMember(Value = "Trader")]
            Trader
        }


        /// <summary>
        /// roles_at_base string
        /// </summary>
        /// <value>roles_at_base string</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum RolesAtBaseEnum
        {
            
            /// <summary>
            /// Enum AccountTake1 for "Account_Take_1"
            /// </summary>
            [EnumMember(Value = "Account_Take_1")]
            AccountTake1,
            
            /// <summary>
            /// Enum AccountTake2 for "Account_Take_2"
            /// </summary>
            [EnumMember(Value = "Account_Take_2")]
            AccountTake2,
            
            /// <summary>
            /// Enum AccountTake3 for "Account_Take_3"
            /// </summary>
            [EnumMember(Value = "Account_Take_3")]
            AccountTake3,
            
            /// <summary>
            /// Enum AccountTake4 for "Account_Take_4"
            /// </summary>
            [EnumMember(Value = "Account_Take_4")]
            AccountTake4,
            
            /// <summary>
            /// Enum AccountTake5 for "Account_Take_5"
            /// </summary>
            [EnumMember(Value = "Account_Take_5")]
            AccountTake5,
            
            /// <summary>
            /// Enum AccountTake6 for "Account_Take_6"
            /// </summary>
            [EnumMember(Value = "Account_Take_6")]
            AccountTake6,
            
            /// <summary>
            /// Enum AccountTake7 for "Account_Take_7"
            /// </summary>
            [EnumMember(Value = "Account_Take_7")]
            AccountTake7,
            
            /// <summary>
            /// Enum Accountant for "Accountant"
            /// </summary>
            [EnumMember(Value = "Accountant")]
            Accountant,
            
            /// <summary>
            /// Enum Auditor for "Auditor"
            /// </summary>
            [EnumMember(Value = "Auditor")]
            Auditor,
            
            /// <summary>
            /// Enum CommunicationsOfficer for "Communications_Officer"
            /// </summary>
            [EnumMember(Value = "Communications_Officer")]
            CommunicationsOfficer,
            
            /// <summary>
            /// Enum ConfigEquipment for "Config_Equipment"
            /// </summary>
            [EnumMember(Value = "Config_Equipment")]
            ConfigEquipment,
            
            /// <summary>
            /// Enum ConfigStarbaseEquipment for "Config_Starbase_Equipment"
            /// </summary>
            [EnumMember(Value = "Config_Starbase_Equipment")]
            ConfigStarbaseEquipment,
            
            /// <summary>
            /// Enum ContainerTake1 for "Container_Take_1"
            /// </summary>
            [EnumMember(Value = "Container_Take_1")]
            ContainerTake1,
            
            /// <summary>
            /// Enum ContainerTake2 for "Container_Take_2"
            /// </summary>
            [EnumMember(Value = "Container_Take_2")]
            ContainerTake2,
            
            /// <summary>
            /// Enum ContainerTake3 for "Container_Take_3"
            /// </summary>
            [EnumMember(Value = "Container_Take_3")]
            ContainerTake3,
            
            /// <summary>
            /// Enum ContainerTake4 for "Container_Take_4"
            /// </summary>
            [EnumMember(Value = "Container_Take_4")]
            ContainerTake4,
            
            /// <summary>
            /// Enum ContainerTake5 for "Container_Take_5"
            /// </summary>
            [EnumMember(Value = "Container_Take_5")]
            ContainerTake5,
            
            /// <summary>
            /// Enum ContainerTake6 for "Container_Take_6"
            /// </summary>
            [EnumMember(Value = "Container_Take_6")]
            ContainerTake6,
            
            /// <summary>
            /// Enum ContainerTake7 for "Container_Take_7"
            /// </summary>
            [EnumMember(Value = "Container_Take_7")]
            ContainerTake7,
            
            /// <summary>
            /// Enum ContractManager for "Contract_Manager"
            /// </summary>
            [EnumMember(Value = "Contract_Manager")]
            ContractManager,
            
            /// <summary>
            /// Enum Diplomat for "Diplomat"
            /// </summary>
            [EnumMember(Value = "Diplomat")]
            Diplomat,
            
            /// <summary>
            /// Enum Director for "Director"
            /// </summary>
            [EnumMember(Value = "Director")]
            Director,
            
            /// <summary>
            /// Enum FactoryManager for "Factory_Manager"
            /// </summary>
            [EnumMember(Value = "Factory_Manager")]
            FactoryManager,
            
            /// <summary>
            /// Enum FittingManager for "Fitting_Manager"
            /// </summary>
            [EnumMember(Value = "Fitting_Manager")]
            FittingManager,
            
            /// <summary>
            /// Enum HangarQuery1 for "Hangar_Query_1"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_1")]
            HangarQuery1,
            
            /// <summary>
            /// Enum HangarQuery2 for "Hangar_Query_2"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_2")]
            HangarQuery2,
            
            /// <summary>
            /// Enum HangarQuery3 for "Hangar_Query_3"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_3")]
            HangarQuery3,
            
            /// <summary>
            /// Enum HangarQuery4 for "Hangar_Query_4"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_4")]
            HangarQuery4,
            
            /// <summary>
            /// Enum HangarQuery5 for "Hangar_Query_5"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_5")]
            HangarQuery5,
            
            /// <summary>
            /// Enum HangarQuery6 for "Hangar_Query_6"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_6")]
            HangarQuery6,
            
            /// <summary>
            /// Enum HangarQuery7 for "Hangar_Query_7"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_7")]
            HangarQuery7,
            
            /// <summary>
            /// Enum HangarTake1 for "Hangar_Take_1"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_1")]
            HangarTake1,
            
            /// <summary>
            /// Enum HangarTake2 for "Hangar_Take_2"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_2")]
            HangarTake2,
            
            /// <summary>
            /// Enum HangarTake3 for "Hangar_Take_3"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_3")]
            HangarTake3,
            
            /// <summary>
            /// Enum HangarTake4 for "Hangar_Take_4"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_4")]
            HangarTake4,
            
            /// <summary>
            /// Enum HangarTake5 for "Hangar_Take_5"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_5")]
            HangarTake5,
            
            /// <summary>
            /// Enum HangarTake6 for "Hangar_Take_6"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_6")]
            HangarTake6,
            
            /// <summary>
            /// Enum HangarTake7 for "Hangar_Take_7"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_7")]
            HangarTake7,
            
            /// <summary>
            /// Enum JuniorAccountant for "Junior_Accountant"
            /// </summary>
            [EnumMember(Value = "Junior_Accountant")]
            JuniorAccountant,
            
            /// <summary>
            /// Enum PersonnelManager for "Personnel_Manager"
            /// </summary>
            [EnumMember(Value = "Personnel_Manager")]
            PersonnelManager,
            
            /// <summary>
            /// Enum RentFactoryFacility for "Rent_Factory_Facility"
            /// </summary>
            [EnumMember(Value = "Rent_Factory_Facility")]
            RentFactoryFacility,
            
            /// <summary>
            /// Enum RentOffice for "Rent_Office"
            /// </summary>
            [EnumMember(Value = "Rent_Office")]
            RentOffice,
            
            /// <summary>
            /// Enum RentResearchFacility for "Rent_Research_Facility"
            /// </summary>
            [EnumMember(Value = "Rent_Research_Facility")]
            RentResearchFacility,
            
            /// <summary>
            /// Enum SecurityOfficer for "Security_Officer"
            /// </summary>
            [EnumMember(Value = "Security_Officer")]
            SecurityOfficer,
            
            /// <summary>
            /// Enum StarbaseDefenseOperator for "Starbase_Defense_Operator"
            /// </summary>
            [EnumMember(Value = "Starbase_Defense_Operator")]
            StarbaseDefenseOperator,
            
            /// <summary>
            /// Enum StarbaseFuelTechnician for "Starbase_Fuel_Technician"
            /// </summary>
            [EnumMember(Value = "Starbase_Fuel_Technician")]
            StarbaseFuelTechnician,
            
            /// <summary>
            /// Enum StationManager for "Station_Manager"
            /// </summary>
            [EnumMember(Value = "Station_Manager")]
            StationManager,
            
            /// <summary>
            /// Enum Trader for "Trader"
            /// </summary>
            [EnumMember(Value = "Trader")]
            Trader
        }


        /// <summary>
        /// roles_at_hq string
        /// </summary>
        /// <value>roles_at_hq string</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum RolesAtHqEnum
        {
            
            /// <summary>
            /// Enum AccountTake1 for "Account_Take_1"
            /// </summary>
            [EnumMember(Value = "Account_Take_1")]
            AccountTake1,
            
            /// <summary>
            /// Enum AccountTake2 for "Account_Take_2"
            /// </summary>
            [EnumMember(Value = "Account_Take_2")]
            AccountTake2,
            
            /// <summary>
            /// Enum AccountTake3 for "Account_Take_3"
            /// </summary>
            [EnumMember(Value = "Account_Take_3")]
            AccountTake3,
            
            /// <summary>
            /// Enum AccountTake4 for "Account_Take_4"
            /// </summary>
            [EnumMember(Value = "Account_Take_4")]
            AccountTake4,
            
            /// <summary>
            /// Enum AccountTake5 for "Account_Take_5"
            /// </summary>
            [EnumMember(Value = "Account_Take_5")]
            AccountTake5,
            
            /// <summary>
            /// Enum AccountTake6 for "Account_Take_6"
            /// </summary>
            [EnumMember(Value = "Account_Take_6")]
            AccountTake6,
            
            /// <summary>
            /// Enum AccountTake7 for "Account_Take_7"
            /// </summary>
            [EnumMember(Value = "Account_Take_7")]
            AccountTake7,
            
            /// <summary>
            /// Enum Accountant for "Accountant"
            /// </summary>
            [EnumMember(Value = "Accountant")]
            Accountant,
            
            /// <summary>
            /// Enum Auditor for "Auditor"
            /// </summary>
            [EnumMember(Value = "Auditor")]
            Auditor,
            
            /// <summary>
            /// Enum CommunicationsOfficer for "Communications_Officer"
            /// </summary>
            [EnumMember(Value = "Communications_Officer")]
            CommunicationsOfficer,
            
            /// <summary>
            /// Enum ConfigEquipment for "Config_Equipment"
            /// </summary>
            [EnumMember(Value = "Config_Equipment")]
            ConfigEquipment,
            
            /// <summary>
            /// Enum ConfigStarbaseEquipment for "Config_Starbase_Equipment"
            /// </summary>
            [EnumMember(Value = "Config_Starbase_Equipment")]
            ConfigStarbaseEquipment,
            
            /// <summary>
            /// Enum ContainerTake1 for "Container_Take_1"
            /// </summary>
            [EnumMember(Value = "Container_Take_1")]
            ContainerTake1,
            
            /// <summary>
            /// Enum ContainerTake2 for "Container_Take_2"
            /// </summary>
            [EnumMember(Value = "Container_Take_2")]
            ContainerTake2,
            
            /// <summary>
            /// Enum ContainerTake3 for "Container_Take_3"
            /// </summary>
            [EnumMember(Value = "Container_Take_3")]
            ContainerTake3,
            
            /// <summary>
            /// Enum ContainerTake4 for "Container_Take_4"
            /// </summary>
            [EnumMember(Value = "Container_Take_4")]
            ContainerTake4,
            
            /// <summary>
            /// Enum ContainerTake5 for "Container_Take_5"
            /// </summary>
            [EnumMember(Value = "Container_Take_5")]
            ContainerTake5,
            
            /// <summary>
            /// Enum ContainerTake6 for "Container_Take_6"
            /// </summary>
            [EnumMember(Value = "Container_Take_6")]
            ContainerTake6,
            
            /// <summary>
            /// Enum ContainerTake7 for "Container_Take_7"
            /// </summary>
            [EnumMember(Value = "Container_Take_7")]
            ContainerTake7,
            
            /// <summary>
            /// Enum ContractManager for "Contract_Manager"
            /// </summary>
            [EnumMember(Value = "Contract_Manager")]
            ContractManager,
            
            /// <summary>
            /// Enum Diplomat for "Diplomat"
            /// </summary>
            [EnumMember(Value = "Diplomat")]
            Diplomat,
            
            /// <summary>
            /// Enum Director for "Director"
            /// </summary>
            [EnumMember(Value = "Director")]
            Director,
            
            /// <summary>
            /// Enum FactoryManager for "Factory_Manager"
            /// </summary>
            [EnumMember(Value = "Factory_Manager")]
            FactoryManager,
            
            /// <summary>
            /// Enum FittingManager for "Fitting_Manager"
            /// </summary>
            [EnumMember(Value = "Fitting_Manager")]
            FittingManager,
            
            /// <summary>
            /// Enum HangarQuery1 for "Hangar_Query_1"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_1")]
            HangarQuery1,
            
            /// <summary>
            /// Enum HangarQuery2 for "Hangar_Query_2"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_2")]
            HangarQuery2,
            
            /// <summary>
            /// Enum HangarQuery3 for "Hangar_Query_3"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_3")]
            HangarQuery3,
            
            /// <summary>
            /// Enum HangarQuery4 for "Hangar_Query_4"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_4")]
            HangarQuery4,
            
            /// <summary>
            /// Enum HangarQuery5 for "Hangar_Query_5"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_5")]
            HangarQuery5,
            
            /// <summary>
            /// Enum HangarQuery6 for "Hangar_Query_6"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_6")]
            HangarQuery6,
            
            /// <summary>
            /// Enum HangarQuery7 for "Hangar_Query_7"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_7")]
            HangarQuery7,
            
            /// <summary>
            /// Enum HangarTake1 for "Hangar_Take_1"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_1")]
            HangarTake1,
            
            /// <summary>
            /// Enum HangarTake2 for "Hangar_Take_2"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_2")]
            HangarTake2,
            
            /// <summary>
            /// Enum HangarTake3 for "Hangar_Take_3"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_3")]
            HangarTake3,
            
            /// <summary>
            /// Enum HangarTake4 for "Hangar_Take_4"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_4")]
            HangarTake4,
            
            /// <summary>
            /// Enum HangarTake5 for "Hangar_Take_5"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_5")]
            HangarTake5,
            
            /// <summary>
            /// Enum HangarTake6 for "Hangar_Take_6"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_6")]
            HangarTake6,
            
            /// <summary>
            /// Enum HangarTake7 for "Hangar_Take_7"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_7")]
            HangarTake7,
            
            /// <summary>
            /// Enum JuniorAccountant for "Junior_Accountant"
            /// </summary>
            [EnumMember(Value = "Junior_Accountant")]
            JuniorAccountant,
            
            /// <summary>
            /// Enum PersonnelManager for "Personnel_Manager"
            /// </summary>
            [EnumMember(Value = "Personnel_Manager")]
            PersonnelManager,
            
            /// <summary>
            /// Enum RentFactoryFacility for "Rent_Factory_Facility"
            /// </summary>
            [EnumMember(Value = "Rent_Factory_Facility")]
            RentFactoryFacility,
            
            /// <summary>
            /// Enum RentOffice for "Rent_Office"
            /// </summary>
            [EnumMember(Value = "Rent_Office")]
            RentOffice,
            
            /// <summary>
            /// Enum RentResearchFacility for "Rent_Research_Facility"
            /// </summary>
            [EnumMember(Value = "Rent_Research_Facility")]
            RentResearchFacility,
            
            /// <summary>
            /// Enum SecurityOfficer for "Security_Officer"
            /// </summary>
            [EnumMember(Value = "Security_Officer")]
            SecurityOfficer,
            
            /// <summary>
            /// Enum StarbaseDefenseOperator for "Starbase_Defense_Operator"
            /// </summary>
            [EnumMember(Value = "Starbase_Defense_Operator")]
            StarbaseDefenseOperator,
            
            /// <summary>
            /// Enum StarbaseFuelTechnician for "Starbase_Fuel_Technician"
            /// </summary>
            [EnumMember(Value = "Starbase_Fuel_Technician")]
            StarbaseFuelTechnician,
            
            /// <summary>
            /// Enum StationManager for "Station_Manager"
            /// </summary>
            [EnumMember(Value = "Station_Manager")]
            StationManager,
            
            /// <summary>
            /// Enum Trader for "Trader"
            /// </summary>
            [EnumMember(Value = "Trader")]
            Trader
        }


        /// <summary>
        /// roles_at_other string
        /// </summary>
        /// <value>roles_at_other string</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum RolesAtOtherEnum
        {
            
            /// <summary>
            /// Enum AccountTake1 for "Account_Take_1"
            /// </summary>
            [EnumMember(Value = "Account_Take_1")]
            AccountTake1,
            
            /// <summary>
            /// Enum AccountTake2 for "Account_Take_2"
            /// </summary>
            [EnumMember(Value = "Account_Take_2")]
            AccountTake2,
            
            /// <summary>
            /// Enum AccountTake3 for "Account_Take_3"
            /// </summary>
            [EnumMember(Value = "Account_Take_3")]
            AccountTake3,
            
            /// <summary>
            /// Enum AccountTake4 for "Account_Take_4"
            /// </summary>
            [EnumMember(Value = "Account_Take_4")]
            AccountTake4,
            
            /// <summary>
            /// Enum AccountTake5 for "Account_Take_5"
            /// </summary>
            [EnumMember(Value = "Account_Take_5")]
            AccountTake5,
            
            /// <summary>
            /// Enum AccountTake6 for "Account_Take_6"
            /// </summary>
            [EnumMember(Value = "Account_Take_6")]
            AccountTake6,
            
            /// <summary>
            /// Enum AccountTake7 for "Account_Take_7"
            /// </summary>
            [EnumMember(Value = "Account_Take_7")]
            AccountTake7,
            
            /// <summary>
            /// Enum Accountant for "Accountant"
            /// </summary>
            [EnumMember(Value = "Accountant")]
            Accountant,
            
            /// <summary>
            /// Enum Auditor for "Auditor"
            /// </summary>
            [EnumMember(Value = "Auditor")]
            Auditor,
            
            /// <summary>
            /// Enum CommunicationsOfficer for "Communications_Officer"
            /// </summary>
            [EnumMember(Value = "Communications_Officer")]
            CommunicationsOfficer,
            
            /// <summary>
            /// Enum ConfigEquipment for "Config_Equipment"
            /// </summary>
            [EnumMember(Value = "Config_Equipment")]
            ConfigEquipment,
            
            /// <summary>
            /// Enum ConfigStarbaseEquipment for "Config_Starbase_Equipment"
            /// </summary>
            [EnumMember(Value = "Config_Starbase_Equipment")]
            ConfigStarbaseEquipment,
            
            /// <summary>
            /// Enum ContainerTake1 for "Container_Take_1"
            /// </summary>
            [EnumMember(Value = "Container_Take_1")]
            ContainerTake1,
            
            /// <summary>
            /// Enum ContainerTake2 for "Container_Take_2"
            /// </summary>
            [EnumMember(Value = "Container_Take_2")]
            ContainerTake2,
            
            /// <summary>
            /// Enum ContainerTake3 for "Container_Take_3"
            /// </summary>
            [EnumMember(Value = "Container_Take_3")]
            ContainerTake3,
            
            /// <summary>
            /// Enum ContainerTake4 for "Container_Take_4"
            /// </summary>
            [EnumMember(Value = "Container_Take_4")]
            ContainerTake4,
            
            /// <summary>
            /// Enum ContainerTake5 for "Container_Take_5"
            /// </summary>
            [EnumMember(Value = "Container_Take_5")]
            ContainerTake5,
            
            /// <summary>
            /// Enum ContainerTake6 for "Container_Take_6"
            /// </summary>
            [EnumMember(Value = "Container_Take_6")]
            ContainerTake6,
            
            /// <summary>
            /// Enum ContainerTake7 for "Container_Take_7"
            /// </summary>
            [EnumMember(Value = "Container_Take_7")]
            ContainerTake7,
            
            /// <summary>
            /// Enum ContractManager for "Contract_Manager"
            /// </summary>
            [EnumMember(Value = "Contract_Manager")]
            ContractManager,
            
            /// <summary>
            /// Enum Diplomat for "Diplomat"
            /// </summary>
            [EnumMember(Value = "Diplomat")]
            Diplomat,
            
            /// <summary>
            /// Enum Director for "Director"
            /// </summary>
            [EnumMember(Value = "Director")]
            Director,
            
            /// <summary>
            /// Enum FactoryManager for "Factory_Manager"
            /// </summary>
            [EnumMember(Value = "Factory_Manager")]
            FactoryManager,
            
            /// <summary>
            /// Enum FittingManager for "Fitting_Manager"
            /// </summary>
            [EnumMember(Value = "Fitting_Manager")]
            FittingManager,
            
            /// <summary>
            /// Enum HangarQuery1 for "Hangar_Query_1"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_1")]
            HangarQuery1,
            
            /// <summary>
            /// Enum HangarQuery2 for "Hangar_Query_2"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_2")]
            HangarQuery2,
            
            /// <summary>
            /// Enum HangarQuery3 for "Hangar_Query_3"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_3")]
            HangarQuery3,
            
            /// <summary>
            /// Enum HangarQuery4 for "Hangar_Query_4"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_4")]
            HangarQuery4,
            
            /// <summary>
            /// Enum HangarQuery5 for "Hangar_Query_5"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_5")]
            HangarQuery5,
            
            /// <summary>
            /// Enum HangarQuery6 for "Hangar_Query_6"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_6")]
            HangarQuery6,
            
            /// <summary>
            /// Enum HangarQuery7 for "Hangar_Query_7"
            /// </summary>
            [EnumMember(Value = "Hangar_Query_7")]
            HangarQuery7,
            
            /// <summary>
            /// Enum HangarTake1 for "Hangar_Take_1"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_1")]
            HangarTake1,
            
            /// <summary>
            /// Enum HangarTake2 for "Hangar_Take_2"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_2")]
            HangarTake2,
            
            /// <summary>
            /// Enum HangarTake3 for "Hangar_Take_3"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_3")]
            HangarTake3,
            
            /// <summary>
            /// Enum HangarTake4 for "Hangar_Take_4"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_4")]
            HangarTake4,
            
            /// <summary>
            /// Enum HangarTake5 for "Hangar_Take_5"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_5")]
            HangarTake5,
            
            /// <summary>
            /// Enum HangarTake6 for "Hangar_Take_6"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_6")]
            HangarTake6,
            
            /// <summary>
            /// Enum HangarTake7 for "Hangar_Take_7"
            /// </summary>
            [EnumMember(Value = "Hangar_Take_7")]
            HangarTake7,
            
            /// <summary>
            /// Enum JuniorAccountant for "Junior_Accountant"
            /// </summary>
            [EnumMember(Value = "Junior_Accountant")]
            JuniorAccountant,
            
            /// <summary>
            /// Enum PersonnelManager for "Personnel_Manager"
            /// </summary>
            [EnumMember(Value = "Personnel_Manager")]
            PersonnelManager,
            
            /// <summary>
            /// Enum RentFactoryFacility for "Rent_Factory_Facility"
            /// </summary>
            [EnumMember(Value = "Rent_Factory_Facility")]
            RentFactoryFacility,
            
            /// <summary>
            /// Enum RentOffice for "Rent_Office"
            /// </summary>
            [EnumMember(Value = "Rent_Office")]
            RentOffice,
            
            /// <summary>
            /// Enum RentResearchFacility for "Rent_Research_Facility"
            /// </summary>
            [EnumMember(Value = "Rent_Research_Facility")]
            RentResearchFacility,
            
            /// <summary>
            /// Enum SecurityOfficer for "Security_Officer"
            /// </summary>
            [EnumMember(Value = "Security_Officer")]
            SecurityOfficer,
            
            /// <summary>
            /// Enum StarbaseDefenseOperator for "Starbase_Defense_Operator"
            /// </summary>
            [EnumMember(Value = "Starbase_Defense_Operator")]
            StarbaseDefenseOperator,
            
            /// <summary>
            /// Enum StarbaseFuelTechnician for "Starbase_Fuel_Technician"
            /// </summary>
            [EnumMember(Value = "Starbase_Fuel_Technician")]
            StarbaseFuelTechnician,
            
            /// <summary>
            /// Enum StationManager for "Station_Manager"
            /// </summary>
            [EnumMember(Value = "Station_Manager")]
            StationManager,
            
            /// <summary>
            /// Enum Trader for "Trader"
            /// </summary>
            [EnumMember(Value = "Trader")]
            Trader
        }

        /// <summary>
        /// grantable_roles array
        /// </summary>
        /// <value>grantable_roles array</value>
        [DataMember(Name="grantable_roles", EmitDefaultValue=false)]
        public List<GrantableRolesEnum> GrantableRoles { get; set; }
        /// <summary>
        /// grantable_roles_at_base array
        /// </summary>
        /// <value>grantable_roles_at_base array</value>
        [DataMember(Name="grantable_roles_at_base", EmitDefaultValue=false)]
        public List<GrantableRolesAtBaseEnum> GrantableRolesAtBase { get; set; }
        /// <summary>
        /// grantable_roles_at_hq array
        /// </summary>
        /// <value>grantable_roles_at_hq array</value>
        [DataMember(Name="grantable_roles_at_hq", EmitDefaultValue=false)]
        public List<GrantableRolesAtHqEnum> GrantableRolesAtHq { get; set; }
        /// <summary>
        /// grantable_roles_at_other array
        /// </summary>
        /// <value>grantable_roles_at_other array</value>
        [DataMember(Name="grantable_roles_at_other", EmitDefaultValue=false)]
        public List<GrantableRolesAtOtherEnum> GrantableRolesAtOther { get; set; }
        /// <summary>
        /// roles array
        /// </summary>
        /// <value>roles array</value>
        [DataMember(Name="roles", EmitDefaultValue=false)]
        public List<RolesEnum> Roles { get; set; }
        /// <summary>
        /// roles_at_base array
        /// </summary>
        /// <value>roles_at_base array</value>
        [DataMember(Name="roles_at_base", EmitDefaultValue=false)]
        public List<RolesAtBaseEnum> RolesAtBase { get; set; }
        /// <summary>
        /// roles_at_hq array
        /// </summary>
        /// <value>roles_at_hq array</value>
        [DataMember(Name="roles_at_hq", EmitDefaultValue=false)]
        public List<RolesAtHqEnum> RolesAtHq { get; set; }
        /// <summary>
        /// roles_at_other array
        /// </summary>
        /// <value>roles_at_other array</value>
        [DataMember(Name="roles_at_other", EmitDefaultValue=false)]
        public List<RolesAtOtherEnum> RolesAtOther { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetCorporationsCorporationIdRoles200Ok" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetCorporationsCorporationIdRoles200Ok() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetCorporationsCorporationIdRoles200Ok" /> class.
        /// </summary>
        /// <param name="CharacterId">character_id integer (required).</param>
        /// <param name="GrantableRoles">grantable_roles array.</param>
        /// <param name="GrantableRolesAtBase">grantable_roles_at_base array.</param>
        /// <param name="GrantableRolesAtHq">grantable_roles_at_hq array.</param>
        /// <param name="GrantableRolesAtOther">grantable_roles_at_other array.</param>
        /// <param name="Roles">roles array.</param>
        /// <param name="RolesAtBase">roles_at_base array.</param>
        /// <param name="RolesAtHq">roles_at_hq array.</param>
        /// <param name="RolesAtOther">roles_at_other array.</param>
        public GetCorporationsCorporationIdRoles200Ok(int? CharacterId = default(int?), List<GrantableRolesEnum> GrantableRoles = default(List<GrantableRolesEnum>), List<GrantableRolesAtBaseEnum> GrantableRolesAtBase = default(List<GrantableRolesAtBaseEnum>), List<GrantableRolesAtHqEnum> GrantableRolesAtHq = default(List<GrantableRolesAtHqEnum>), List<GrantableRolesAtOtherEnum> GrantableRolesAtOther = default(List<GrantableRolesAtOtherEnum>), List<RolesEnum> Roles = default(List<RolesEnum>), List<RolesAtBaseEnum> RolesAtBase = default(List<RolesAtBaseEnum>), List<RolesAtHqEnum> RolesAtHq = default(List<RolesAtHqEnum>), List<RolesAtOtherEnum> RolesAtOther = default(List<RolesAtOtherEnum>))
        {
            // to ensure "CharacterId" is required (not null)
            if (CharacterId == null)
            {
                throw new InvalidDataException("CharacterId is a required property for GetCorporationsCorporationIdRoles200Ok and cannot be null");
            }
            else
            {
                this.CharacterId = CharacterId;
            }
            this.GrantableRoles = GrantableRoles;
            this.GrantableRolesAtBase = GrantableRolesAtBase;
            this.GrantableRolesAtHq = GrantableRolesAtHq;
            this.GrantableRolesAtOther = GrantableRolesAtOther;
            this.Roles = Roles;
            this.RolesAtBase = RolesAtBase;
            this.RolesAtHq = RolesAtHq;
            this.RolesAtOther = RolesAtOther;
        }
        
        /// <summary>
        /// character_id integer
        /// </summary>
        /// <value>character_id integer</value>
        [DataMember(Name="character_id", EmitDefaultValue=false)]
        public int? CharacterId { get; set; }









        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetCorporationsCorporationIdRoles200Ok {\n");
            sb.Append("  CharacterId: ").Append(CharacterId).Append("\n");
            sb.Append("  GrantableRoles: ").Append(GrantableRoles).Append("\n");
            sb.Append("  GrantableRolesAtBase: ").Append(GrantableRolesAtBase).Append("\n");
            sb.Append("  GrantableRolesAtHq: ").Append(GrantableRolesAtHq).Append("\n");
            sb.Append("  GrantableRolesAtOther: ").Append(GrantableRolesAtOther).Append("\n");
            sb.Append("  Roles: ").Append(Roles).Append("\n");
            sb.Append("  RolesAtBase: ").Append(RolesAtBase).Append("\n");
            sb.Append("  RolesAtHq: ").Append(RolesAtHq).Append("\n");
            sb.Append("  RolesAtOther: ").Append(RolesAtOther).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetCorporationsCorporationIdRoles200Ok);
        }

        /// <summary>
        /// Returns true if GetCorporationsCorporationIdRoles200Ok instances are equal
        /// </summary>
        /// <param name="input">Instance of GetCorporationsCorporationIdRoles200Ok to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetCorporationsCorporationIdRoles200Ok input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CharacterId == input.CharacterId ||
                    (this.CharacterId != null &&
                    this.CharacterId.Equals(input.CharacterId))
                ) && 
                (
                    this.GrantableRoles == input.GrantableRoles ||
                    (this.GrantableRoles != null &&
                    this.GrantableRoles.SequenceEqual(input.GrantableRoles))
                ) && 
                (
                    this.GrantableRolesAtBase == input.GrantableRolesAtBase ||
                    (this.GrantableRolesAtBase != null &&
                    this.GrantableRolesAtBase.SequenceEqual(input.GrantableRolesAtBase))
                ) && 
                (
                    this.GrantableRolesAtHq == input.GrantableRolesAtHq ||
                    (this.GrantableRolesAtHq != null &&
                    this.GrantableRolesAtHq.SequenceEqual(input.GrantableRolesAtHq))
                ) && 
                (
                    this.GrantableRolesAtOther == input.GrantableRolesAtOther ||
                    (this.GrantableRolesAtOther != null &&
                    this.GrantableRolesAtOther.SequenceEqual(input.GrantableRolesAtOther))
                ) && 
                (
                    this.Roles == input.Roles ||
                    (this.Roles != null &&
                    this.Roles.SequenceEqual(input.Roles))
                ) && 
                (
                    this.RolesAtBase == input.RolesAtBase ||
                    (this.RolesAtBase != null &&
                    this.RolesAtBase.SequenceEqual(input.RolesAtBase))
                ) && 
                (
                    this.RolesAtHq == input.RolesAtHq ||
                    (this.RolesAtHq != null &&
                    this.RolesAtHq.SequenceEqual(input.RolesAtHq))
                ) && 
                (
                    this.RolesAtOther == input.RolesAtOther ||
                    (this.RolesAtOther != null &&
                    this.RolesAtOther.SequenceEqual(input.RolesAtOther))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CharacterId != null)
                    hashCode = hashCode * 59 + this.CharacterId.GetHashCode();
                if (this.GrantableRoles != null)
                    hashCode = hashCode * 59 + this.GrantableRoles.GetHashCode();
                if (this.GrantableRolesAtBase != null)
                    hashCode = hashCode * 59 + this.GrantableRolesAtBase.GetHashCode();
                if (this.GrantableRolesAtHq != null)
                    hashCode = hashCode * 59 + this.GrantableRolesAtHq.GetHashCode();
                if (this.GrantableRolesAtOther != null)
                    hashCode = hashCode * 59 + this.GrantableRolesAtOther.GetHashCode();
                if (this.Roles != null)
                    hashCode = hashCode * 59 + this.Roles.GetHashCode();
                if (this.RolesAtBase != null)
                    hashCode = hashCode * 59 + this.RolesAtBase.GetHashCode();
                if (this.RolesAtHq != null)
                    hashCode = hashCode * 59 + this.RolesAtHq.GetHashCode();
                if (this.RolesAtOther != null)
                    hashCode = hashCode * 59 + this.RolesAtOther.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
