/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.2.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Eve.Api.Client.SwaggerDateConverter;

namespace Eve.Api.Model
{
    /// <summary>
    /// response object
    /// </summary>
    [DataContract]
    public partial class PutCharactersCharacterIdCalendarEventIdResponse :  IEquatable<PutCharactersCharacterIdCalendarEventIdResponse>, IValidatableObject
    {
        /// <summary>
        /// response string
        /// </summary>
        /// <value>response string</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ResponseEnum
        {
            
            /// <summary>
            /// Enum Accepted for "accepted"
            /// </summary>
            [EnumMember(Value = "accepted")]
            Accepted,
            
            /// <summary>
            /// Enum Declined for "declined"
            /// </summary>
            [EnumMember(Value = "declined")]
            Declined,
            
            /// <summary>
            /// Enum Tentative for "tentative"
            /// </summary>
            [EnumMember(Value = "tentative")]
            Tentative
        }

        /// <summary>
        /// response string
        /// </summary>
        /// <value>response string</value>
        [DataMember(Name="response", EmitDefaultValue=false)]
        public ResponseEnum? Response { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PutCharactersCharacterIdCalendarEventIdResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PutCharactersCharacterIdCalendarEventIdResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PutCharactersCharacterIdCalendarEventIdResponse" /> class.
        /// </summary>
        /// <param name="Response">response string (required).</param>
        public PutCharactersCharacterIdCalendarEventIdResponse(ResponseEnum? Response = default(ResponseEnum?))
        {
            // to ensure "Response" is required (not null)
            if (Response == null)
            {
                throw new InvalidDataException("Response is a required property for PutCharactersCharacterIdCalendarEventIdResponse and cannot be null");
            }
            else
            {
                this.Response = Response;
            }
        }
        

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PutCharactersCharacterIdCalendarEventIdResponse {\n");
            sb.Append("  Response: ").Append(Response).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PutCharactersCharacterIdCalendarEventIdResponse);
        }

        /// <summary>
        /// Returns true if PutCharactersCharacterIdCalendarEventIdResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of PutCharactersCharacterIdCalendarEventIdResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PutCharactersCharacterIdCalendarEventIdResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Response == input.Response ||
                    (this.Response != null &&
                    this.Response.Equals(input.Response))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Response != null)
                    hashCode = hashCode * 59 + this.Response.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
